#! /usr/bin/env -S bash -e

DIR=$(dirname $(readlink -f $0))

unset PYTHONPATH
export PYTHONPATH=$DIR
#source $DIR/venv/bin/activate # TODO: get this working in pipenv or something to make it portable
sudo /usr/bin/env python3 $DIR/src/python/snoopy.py $*
